// 54 settlements
/*

TODO:
 - Add City Attribute?
 - 
 - 

*/

var settlements = []
export default settlements = [
    {
        "index": 0,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [0],
        connectedRoads: [0, 1],
        port: "1a",
    },
    {
        "index": 1,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [1],
        connectedRoads: [2, 3],
        port: "2a",
    },
    {
        "index": 2,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [2],
        connectedRoads: [4, 5],
        port: null,
    },
    {
        "index": 3,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [0],
        connectedRoads: [0, 6],
        port: "1b",
    },
    {
        "index": 4,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [0, 1],
        connectedRoads: [1, 2, 7],
        port: null,
    },
    {
        "index": 5,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [1, 2],
        connectedRoads: [3, 4, 8],
        port: "2b",
    },
    {
        "index": 6,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [2],
        connectedRoads: [5, 9],
        port: null,
    },
    {
        "index": 7,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [0, 3],
        connectedRoads: [6, 10, 11],
        port: null,
    },
    {
        "index": 8,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [0, 1, 4],
        connectedRoads: [7, 12, 13],
        port: null,
    },
    {
        "index": 9,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [1, 2, 5],
        connectedRoads: [8, 14, 15],
        port: null,
    },
    {
        "index": 10,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [2, 6],
        connectedRoads: [9, 16, 17],
        port: "3a",
    },
    {
        "index": 11,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [3],
        connectedRoads: [10, 18],
        port: "4a",
    },
    {
        "index": 12,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [0, 3, 4],
        connectedRoads: [11, 12, 19],
        port: null,
    },
    {
        "index": 13,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [1, 4, 5],
        connectedRoads: [13, 14, 20],
        port: null,
    },
    {
        "index": 14,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [2, 5, 6],
        connectedRoads: [15, 16, 21],
        port: null,
    },
    {
        "index": 15,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [6],
        connectedRoads: [17, 22],
        port: "3b",
    },
    {
        "index": 16,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [3, 7],
        connectedRoads: [18, 23, 24],
        port: "4b",
    },
    {
        "index": 17,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [3, 4, 8],
        connectedRoads: [19, 25, 26],
        port: null,
    },
    {
        "index": 18,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [4, 5, 9],
        connectedRoads: [20, 27, 28],
        port: null,
    },
    {
        "index": 19,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [5, 6, 10],
        connectedRoads: [21, 29, 30],
        port: null,
    },
    {
        "index": 20,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [6, 11],
        connectedRoads: [22, 31, 32],
        port: null,
    },
    {
        "index": 21,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [7],
        connectedRoads: [23, 33],
        port: null,
    },
    {
        "index": 22,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [3, 7, 8],
        connectedRoads: [24, 25, 34],
        port: null,
    },
    {
        "index": 23,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [4, 8, 9],
        connectedRoads: [26, 27, 35],
        port: null,
    },
    {
        "index": 24,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [5, 9, 10],
        connectedRoads: [28, 29, 36],
        port: null,
    },
    {
        "index": 25,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [6, 10, 11],
        connectedRoads: [30, 31, 37],
        port: null,
    },
    {
        "index": 26,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [11],
        connectedRoads: [32, 38],
        port: "5a",
    },
    {
        "index": 27,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [7],
        connectedRoads: [33, 39],
        port: null,
    },
    {
        "index": 28,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [7, 8, 12],
        connectedRoads: [34, 40, 41],
        port: null,
    },
    {
        "index": 29,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [8, 9, 13],
        connectedRoads: [35, 42, 43],
        port: null,
    },
    {
        "index": 30,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [9, 10, 14],
        connectedRoads: [36, 44, 45],
        port: null,
    },
    {
        "index": 31,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [10, 11, 15],
        connectedRoads: [37, 46, 47],
        port: null,
    },
    {
        "index": 32,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [11],
        connectedRoads: [38, 48],
        port: "5b",
    },
    {
        "index": 33,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [7, 12],
        connectedRoads: [39, 40, 49],
        port: "6a",
    },
    {
        "index": 34,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [8, 12, 13],
        connectedRoads: [41, 42, 50],
        port: null,
    },
    {
        "index": 35,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [9, 13, 14],
        connectedRoads: [43, 44, 51],
        port: null,
    },
    {
        "index": 36,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [10, 14, 15],
        connectedRoads: [45, 46, 52],
        port: null,
    },
    {
        "index": 37,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [11, 15],
        connectedRoads: [47, 48, 53],
        port: null,
    },
    {
        "index": 38,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [12],
        connectedRoads: [49, 54],
        port: "6b",
    },
    {
        "index": 39,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [12, 13, 16],
        connectedRoads: [50, 55, 56],
        port: null,
    },
    {
        "index": 40,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [13, 14, 17],
        connectedRoads: [51, 57, 58],
        port: null,
    },
    {
        "index": 41,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [14, 15, 18],
        connectedRoads: [52, 59, 60],
        port: null,
    },
    {
        "index": 42,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [15],
        connectedRoads: [53, 61],
        port: "7a",
    },
    {
        "index": 43,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [12, 16],
        connectedRoads: [54, 55, 62],
        port: null,
    },
    {
        "index": 44,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [13, 16, 17],
        connectedRoads: [56, 57, 63],
        port: null,
    },
    {
        "index": 45,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [14, 17, 18],
        connectedRoads: [58, 59, 64],
        port: null,
    },
    {
        "index": 46,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [15, 18],
        connectedRoads: [60, 61, 65],
        port: "7b",
    },
    {
        "index": 47,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [16],
        connectedRoads: [62, 66],
        port: "8a",
    },
    {
        "index": 48,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [16, 17],
        connectedRoads: [63, 67, 68],
        port: null,
    },
    {
        "index": 49,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [17, 18],
        connectedRoads: [64, 69, 70],
        port: "9a",
    },
    {
        "index": 50,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [18],
        connectedRoads: [65, 71],
        port: null,
    },
    {
        "index": 51,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [16],
        connectedRoads: [66, 67],
        port: "8b",
    },
    {
        "index": 52,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [17],
        connectedRoads: [68, 69],
        port: "9b",
    },
    {
        "index": 53,
        isPossible: true,
        playerSettledBy: 0,
        connectedTiles: [18],
        connectedRoads: [70, 71],
        port: null,
    }
]

